#!/bin/sh
sudo systemctl disable asusgpuboot
sudo cp etc/modprobe.d/asus-linux.conf /etc/modprobe.d/
sudo cp etc/systemd/system/* /etc/systemd/system/
sudo cp usr/local/asus-x13-switching/* /usr/local/asus-x13-switching/
sudo systemctl enable asusgpuboot